language: julia
notifications:
  email: false
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: 1.3
    - julia: nightly
  include:
    - os: linux
      arch: x86
      julia: 1.0
    - os: windows
      arch: x86
      julia: 1.0
    - os: linux
      arch: x86
      julia: 1.1
    - os: windows
      arch: x86
      julia: 1.1
    - os: linux
      arch: x86
      julia: 1.2
    - os: windows
      arch: x86
      julia: 1.2
    - os: linux
      arch: x86
      julia: nightly
    - os: windows
      arch: x86
      julia: nightly
    - stage: Documentation
      julia: 1.0
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(; path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
